# Generated by Django 4.2.7 on 2023-11-28 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='available_seats',
            new_name='seats_available',
        ),
        migrations.AddField(
            model_name='ride',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carpool.car'),
        ),
    ]
