# Generated by Django 4.2.7 on 2023-12-01 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0003_alter_user_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RideReview',
            new_name='RiderReview',
        ),
        migrations.AlterModelTable(
            name='riderreview',
            table='rider_review',
        ),
    ]
