# Generated by Django 4.2.7 on 2023-12-01 01:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0004_rename_ridereview_riderreview_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riderreview',
            name='user',
        ),
        migrations.AddField(
            model_name='riderreview',
            name='passenger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='passenger', to='carpool.user'),
        ),
        migrations.AddField(
            model_name='riderreview',
            name='rider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rider', to='carpool.user'),
        ),
        migrations.AlterField(
            model_name='riderreview',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='riderreview',
            name='ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='carpool.ride'),
        ),
    ]
