# Generated by Django 4.2.7 on 2023-12-01 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0005_remove_riderreview_user_riderreview_passenger_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riderreview',
            name='rider',
        ),
    ]
