# Generated by Django 4.2.7 on 2023-12-01 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0007_rename_riderreview_driverreview_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpool.ride')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='carpool.user')),
            ],
            options={
                'db_table': 'message',
                'ordering': ['-created_at'],
            },
        ),
    ]
