# Generated by Django 4.2.7 on 2023-12-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0009_user_from_location_user_speaks_user_studies'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cover_photo_url',
            field=models.ImageField(blank=True, null=True, upload_to='cover_photo_images/'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo_url',
            field=models.ImageField(blank=True, null=True, upload_to='photo_images/'),
        ),
    ]
