# Generated by Django 4.2.7 on 2023-12-03 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0011_user_cover_photo_base64_user_profile_photo_base64'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cover_photo_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='photo_url',
        ),
    ]
