# Generated by Django 4.2.7 on 2023-12-04 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0013_ridepassenger_drop_off_coordinates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='speaks',
            field=models.JSONField(blank=True, default=[], null=True),
        ),
    ]
