# Generated by Django 4.2.7 on 2023-12-04 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0014_alter_user_speaks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='from_location',
            field=models.CharField(default='San Marcos, TX', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='studies',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
